### ISSUE TITLE
How to combine multi flows from different apis?

### ISSUE THREAD

**Issue by ageback** [hadiyarajesh/flower#11]
I'm developing a weather app, which fetch weather forecast data from different apis such as Daily, Hourly, AirQuality .etc. I can access each api with one flow. Now I want to combine these flows into one and return it in one callback. How can I do it with Flower lib, please?

**Comment by hadiyarajesh** [comment]
Have you tried using `combine` operator?
More details [here](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/combine.html)

**Comment by ageback** [comment]
Now I use Flow.combineTransform() to implement it. Thanks!
