### ISSUE TITLE
Error class without data

### ISSUE THREAD

**Issue by hadiyarajesh** [hadiyarajesh/flower#32]
Currently, `Error` class is [having access to `nullable` data property](https://github.com/hadiyarajesh/flower/blob/ffe5c74d4ac3daf1299178e666dc48789dbc988b/flower-core/src/commonMain/kotlin/com/hadiyarajesh/flower_core/Resource.kt#L29)

We're providing local data in case of network error response, but I believe we should remove that data field and `Error` class should only contains errorMsg and status code.

Additionally, planning use errorMsg and statusCode as value class instead of primitives.

@DATL4G what are your thougths?

**Comment by DATL4G** [comment]
I already thought about that and wanted to do that.
However there is a use case that prevents this.

https://github.com/hadiyarajesh/flower/blob/master/flower-core/src/commonMain/kotlin/com/hadiyarajesh/flower_core/DBBoundResource.kt#L66

Even if the API access fails we want to get new values from the database (e.g. if the user updates the value himself)

**Comment by hadiyarajesh** [comment]
Got it. So let it be.

I also thought to provide a class to get local db resource in order to monitor it's status (loading/success) 

[Have a look](https://github.com/hadiyarajesh/flower/blob/feature_use_inline_classes/flower-core/src/commonMain/kotlin/com/hadiyarajesh/flower_core/DBResource.kt)

**Comment by hadiyarajesh** [comment]
Hey, @DATL4G 

I've created a [PR](https://github.com/hadiyarajesh/flower/pull/34) with few features.
Can you have a look and make it compatible with the latest ktorfit library?

I can see we've `FlowerResponseConverter` in `ktorfit` package but not using it anywhere. Is it something we can get rid of?

**Comment by hadiyarajesh** [comment]
Resolved with PR https://github.com/hadiyarajesh/flower/pull/34
