### ISSUE TITLE
can demo use flower-ktorfit?

### ISSUE THREAD

**Issue by CMingTseng** [hadiyarajesh/flower#33]
Dear Sir

i  follow  "ktorfit"

as the issus   https://github.com/Foso/Ktorfit/issues/85

you say  https://github.com/Foso/Ktorfit/issues/85#issuecomment-1294224913

so i go to here 

can demo how use flower-ktorfit ?

THX

**Comment by hadiyarajesh** [comment]
Yes, demo is mentioned in [README](https://github.com/hadiyarajesh/flower/blob/master/README.md) file under `Installation` section for `ktorifit`. Try it and it need more help, make a comment here.

**Comment by hadiyarajesh** [comment]
I'm closing the issue now. Let me know if you need more help.
